107-team2/team2/ntust/mysite/mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from team2 import views
from team2.views import *
from django.conf.urls.static import static
from django.conf import settings
from .settings import MEDIA_ROOT
from django.views.static import serve


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^team2/', include('team2.urls')) ,
    url(r'^team2/my.html/$', post_detail1, name='post_detail1'),
    url(r'^team2/(?P<pk>[0-9]+)/$', post_area, name='post_area'),
    url(r'^team2/about.html/$', post_about, name='post_about'),
    url(r'^team2/m(?P<pk>[0-9]+)/$', post_museum, name='post_museum'),
    url(r'^team2/t(?P<pk>[0-9]+)/$', post_m_type, name='post_m_type'),
    url(r'^team2/c(?P<pk>[0-9]+)/$', comment, name='comment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

107-team2/team2/ntust/mysite/team2/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index , name='index'),
	url(r'^$', views.post_detail1 , name='post_detail1'),
	url(r'^$', views.post_area , name='post_area'),
	url(r'^$', views.post_about , name='post_about'),
	url(r'^$', views.post_museum , name='post_museum'),
	url(r'^$', views.post_m_type , name='post_m_type'),
	url(r'^$', views.comment , name='comment'),
]

107-team2/team2/ntust/mysite/team2/models.py
from django.db import models

# Create your models here.

class Area(models.Model):
    area = models.CharField(max_length=20)

    def __str__(self):
        return self.area

class M_Type(models.Model):
    m_type = models.CharField(max_length=20)

    def __str__(self):
        return self.m_type

class Museum(models.Model):
    name = models.CharField(max_length=20)
    price_adult = models.CharField(max_length=20)
    price_discount = models.CharField(max_length=20)
    time =  models.CharField(max_length=100)
    rest = models.CharField(max_length=100)
    img = models.ImageField(upload_to='media/')
    hy = models.CharField(max_length=600)
    intro = models.CharField(max_length=1000)
    area = models.ForeignKey(Area)
    mtype = models.ForeignKey(M_Type)
    img1 = models.ImageField(upload_to='media/',blank=True)
    img2 = models.ImageField(upload_to='media/',blank=True)
    img3 = models.ImageField(upload_to='media/',blank=True)
    img4 = models.ImageField(upload_to='media/',blank=True)
    img5 = models.ImageField(upload_to='media/',blank=True)

    def __str__(self):
        return self.name


class About(models.Model):
    name = models.CharField(max_length=20)
    sy = models.CharField(max_length=20)
    img = models.ImageField(upload_to='media/')
    def __str__(self):
        return self.name

class home_page(models.Model):
    intro = models.CharField(max_length=300)
    img = models.ImageField(upload_to='media/')
    def __str__(self):
        return self.intro

class Comment(models.Model):
    content = models.CharField(max_length=200)
    user = models.CharField(max_length=20)
    museum = models.ForeignKey(Museum)

    def __str__(self):
        return self.content

107-team2/team2/ntust/mysite/team2/views.py
from django.shortcuts import render_to_response
from django.shortcuts import render
from team2.models import *
# Create your views here.
def index(request):
    m_type = M_Type.objects.all()
    area = Area.objects.all()
    about = About.objects.all()
    museum = Museum.objects.all()
    home = home_page.objects.all()

    content = {'home':home,'museum':museum,'m_type':m_type,'area':area,'about':about}
    return render(request, 'team2/showimg.html', content)

def post_detail1(request):
    m_type = M_Type.objects.all()
    area = Area.objects.all()
    about = About.objects.all()
    museum = Museum.objects.all()
    home = home_page.objects.all()

    content = {'home':home,'museum':museum,'m_type':m_type,'area':area,'about':about}
    return render(request, 'team2/my.html', content)

def post_area(request, pk):
    m_type = M_Type.objects.all()
    area1 = Area.objects.all()
    about = About.objects.all()
    museum = Museum.objects.all()
    home = home_page.objects.all()
    area = Area.objects.get(pk=pk)
    content = {'home':home,'museum':museum,'m_type':m_type,'area':area,'about':about,'area1':area1}
    
    return render(request, 'team2/area.html', content)
def post_about(request):
    m_type = M_Type.objects.all()
    area = Area.objects.all()
    about = About.objects.all()
    museum = Museum.objects.all()
    home = home_page.objects.all()
    content = {'home':home,'museum':museum,'m_type':m_type,'area':area,'about':about}
    
    return render(request, 'team2/about.html', content)
def post_museum(request, pk):
    m_type = M_Type.objects.all()
    area = Area.objects.all()
    about = About.objects.all()
    home = home_page.objects.all()
    museum = Museum.objects.get(pk=pk)
    content = {'home':home,'museum':museum,'m_type':m_type,'area':area,'about':about}
    
    return render(request, 'team2/museum.html', content)
def post_m_type(request, pk):
    m_type1 = M_Type.objects.all()
    area = Area.objects.all()
    about = About.objects.all()
    museum = Museum.objects.all()
    home = home_page.objects.all()
    m_type = M_Type.objects.get(pk=pk)
    content = {'home':home,'museum':museum,'m_type':m_type,'area':area,'about':about,'m_type1':m_type1}

    return render(request, 'team2/m_type.html', content)

def comment(request,pk):

    m_type = M_Type.objects.all()
    area = Area.objects.all()
    about = About.objects.all()
    home = home_page.objects.all()
    museum = Museum.objects.get(pk=pk)
    museum1 = Museum.objects.all()
    user = ''
    content = ''
    if request.method == 'POST':
        content = request.POST.get('content')
        user = request.POST.get('user')
       
        Comment.objects.create(user=user, content=content,museum=museum)

    com = Comment.objects.all()
    
    b= {'content': content,'com':com,'user':user,'museum':museum,'area':area,'about':about,'home':home,'m_type':m_type}
    return render(request, 'team2/comments.html', b)

107-team2/team2/ntust/mysite/team2/templates/team2/about.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-icon.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style4.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://cdn.bootcss.com/animate.css/3.5.1/animate.min.css">
	<style>
    
body {font-family: "Lato", sans-serif,微軟正黑體;}
.mySlides {display: none}
.container-fluid.main{
  position: relative; /* To make the navbar positions relative to this container */
  padding: 0;
}

.navbar-default {
  background-image: none;
  background-color: transparent; /* Make the menu become transparent */
  border-radius: 0px;
  border: 0;
  box-shadow: none
  padding: 0px;
  position: absolute; /* Make the menu out of the document flow so it can placed anywhere without disturbing other widgets */
  top: 0;
  left: 0;
  right: 0;
  z-index: 1; /* If you delete this line, your menu link won't be clicked because it is behind the background. Applying this code bring the menu in front of the background */
}

.navbar-default .navbar-brand {
  font-family: Verdana;
  color: #ffffff;
  font-size: 20px;
}

.navbar-default .navbar-brand:hover,
.navbar-default .navbar-brand:focus {
  color: #ffffff;
  background-color: transparent;
}

.navbar-default .navbar-nav > li > a {
  color: #ffffff;
}

.navbar-default .navbar-nav > li > a:hover,
.navbar-default .navbar-nav > li > a:focus {
  color: #ffffff;
  background-color: transparent;
}

.navbar-default .navbar-toggle {
  border-color: transparent;
}

.navbar-default .navbar-toggle:hover {
  background-color: transparent;
}

.navbar-default .navbar-toggle:focus {
  background-color: transparent;
}

.navbar-default .navbar-toggle .icon-bar {
  background-color: #ffffff;
}

</style>
</head>
<body >
	<div class="container-fluid main">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
<div class="w3-top">
  <div class="w3-bar w3-black w3-card-2">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="/team2/my.html" class="w3-bar-item w3-button w3-padding-large">首頁</a>
    <div class="w3-dropdown-hover w3-hide-small">
      <button class="w3-padding-large w3-button" title="More">地區劃分<i class="fa fa-caret-down"></i></button>     
      <div class="w3-dropdown-content w3-bar-block w3-card-4">

          {% for i in area %}
          <a href="/team2/{{i.pk}}" class="w3-bar-item w3-button">{{i.area}}</a>
          {% endfor %}
      </div>
    </div>
    <div class="w3-dropdown-hover w3-hide-small">
      <button class="w3-padding-large w3-button" title="More">性質劃分<i class="fa fa-caret-down"></i></button>     
      <div class="w3-dropdown-content w3-bar-block w3-card-4">
          {% for i in m_type %}
          <a href="/team2/t{{i.pk}}" class="w3-bar-item w3-button">{{i.m_type}}</a>
          {% endfor %}
      </div>
    </div>
    <a href="/team2/about.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small">關於我們</a>
    
  </div>
</div>
      <!--<div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          
          </ul>
        </div>-->
      </div>
     </nav>
</div>
<section id="teams" class="section teams">
    <div class="container-fluid bg-3 text-center" >
      <div class="section-header"  >
            <h1 class="wow fadeInDown animated" >About Us<small>    It's Nice to Meet You!</small></h1>
            <p class="wow fadeInDown animated">整合台灣各地博物館資訊<br>讓大家休閒時候除了到網美聖地拍照打卡吃美食<br>多一種提升個人內在涵養的選擇</p>
            
            <h2 class="wow fadeInDown animated">Our Team</h2>
           
   <div class="row">
        {% for a in about %}
        <div class="col-lg-3 col-sm-7 text-center mb-4">        
        <div class="person"><img src="{{ a.img.url }}" alt=""/ style="width:180px;height:180px;" class="rounded-circle img-fluid d-block mx-auto">
          <div class="person-content">
            <h4 style="color:black;"><font face="微軟正黑體">{{a.name}}</font></h4> 
            <h4 style="color:black;"><font face="微軟正黑體">{{a.sy}}</font></h4>
          </div>
        </div>
        </div>
        {% endfor %}
      
    </div>

  </div>
  </div>
</section>
</body>
</html>

107-team2/team2/ntust/mysite/team2/templates/team2/area.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
    <meta name = "format-detection" content = "telephone=no" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">  
     <link rel="icon" href="{% static 'images/favicon.ico' %}" >
     <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"  />
     <link  rel="stylesheet" media="screen" href="{% static 'css/style.css' %}">
     <link  rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
     <script src="{% static 'js/jquery.js' %}"></script>
     <script src="{% static 'js/jquery-migrate-1.1.1.js' %}"></script>
     <script src="{% static 'js/script.js' %}"></script> 
     <script src="{% static 'js/jquery.equalheights.js' %}"></script>
     <script src="{% static 'js/superfish.js' %}"></script>
     <script  src="{% static 'js/jquery.responsivemenu.js' %}"></script>
     <script  src="{% static 'js/jquery.mobilemenu.js' %}"></script>
     <script  src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<style>


body {font-family: "Lato", sans-serif;}
.mySlides {display: none}
</style>
</head>
<body>
    <div class="container-fluid main">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
    <div class="w3-top" >
      <div class="w3-bar w3-black w3-card-2">
        <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
        <a href="/team2/my.html" class="w3-bar-item w3-button w3-padding-large">首頁</a>
        <div class="w3-dropdown-hover w3-hide-small">
          <button class="w3-padding-large w3-button" title="More">地區劃分<i class="fa fa-caret-down"></i></button>     
          <div class="w3-dropdown-content w3-bar-block w3-card-4">

              {% for i in area1 %}
              <a href="/team2/{{i.pk}}" class="w3-bar-item w3-button">{{i.area}}</a>
              {% endfor %}
          </div>
        </div>
        <div class="w3-dropdown-hover w3-hide-small">
          <button class="w3-padding-large w3-button" title="More">性質劃分<i class="fa fa-caret-down"></i></button>     
          <div class="w3-dropdown-content w3-bar-block w3-card-4">
              {% for i in m_type %}
              <a href="/team2/t{{i.pk}}" class="w3-bar-item w3-button">{{i.m_type}}</a>
              {% endfor %}
          </div>
        </div>
        <a href="/team2/about.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small">關於我們</a>
        
      </div>
    </div>
          <!--<div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              
              </ul>
            </div>-->
          </div>
         </nav>
    </div>


    	
    <div class="content projects">
        <div class="container_12">
        <div class="grid_12">
          <p align="center"><h1 style="font-family:微軟正黑體;margin-top:70px;margin-bottom:70px;font-size:400%">{{area.area}}</h1></p>
        </div>
        <div class="row" style="font-family:微軟正黑體;">
        <table>
          {% for i in area.museum_set.all %}
          {% if forloop.counter|divisibleby:'4' %}
            <td>
              <div class="grid_3">
                <div class="box ic">
                  <div class="maxheight">
                      <h2 style="font-family:微軟正黑體;">{{i.name}}</h2><h4 style="font-family:微軟正黑體;">{{i.mtype}}</h4><i class=" fa fa-cloud"></i>
                      <p><img src="/media/{{ i.img }}" alt=""/ style="width:200px;height:150px;"></p>
                      
                      <p><a href="/team2/m{{ i.pk }}" class="btn">read more</a></p>
                  </div>
            </td>

          </table>
            {% else %}
          <table>
              <tr>
                <div class="grid_3">
                <div class="box ic">
                  <div class="maxheight">
                      <h2 style="font-family:微軟正黑體;">{{i.name}}</h2><h4 style="font-family:微軟正黑體;">{{i.mtype}}</h4><i class=" fa fa-cloud"></i>
                      <p style="font-family:微軟正黑體;"><img src="/media/{{ i.img }}" alt=""/ style="width:200px;height:150px;"></p>
                      
                      <p><a href="/team2/m{{ i.pk }}" class="btn">read more</a></p>
                  </div>
               </td>
         {% endif %}   
        {% endfor %}
        </table>
        
    </div>

    <!--<section id="teams" class="section teams">
        <div class="container-fluid bg-3 text-center">
          <div class="section-header">
                <h1 class="wow fadeInDown animated">About Us<small>    It's Nice to Meet You!</small></h1>
                <p class="wow fadeInDown animated">整合台灣各地博物館資訊<br>讓大家休閒時候除了到網美聖地拍照打卡吃美食<br>多一種提升個人內在涵養的選擇</p>
                
                <h2 class="wow fadeInDown animated">Our Team</h2>
               
       <div class="row">
            {% for a in about %}
            <div class="col-lg-3 col-sm-7 text-center mb-4">        
            <div class="person"><img src="{{ a.img.url }}" alt=""/ style="width:180px;height:280px:" class="rounded-circle img-fluid d-block mx-auto">
              <div class="person-content">
                <h4>{{a.name}}</h4> 
                <h4>{{a.sy}}</h4>
              </div>
            </div>
            </div>
            {% endfor %}
          
        </div>

      </div>
      </div>
    </section>-->

</body>
</html>

107-team2/team2/ntust/mysite/team2/templates/team2/comments.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif,微軟正黑體;}
.mySlides {display: none}

.container-fluid.main{
  position: relative; /* To make the navbar positions relative to this container */
  padding: 0;
}

.navbar-default {
  background-image: none;
  background-color: transparent; /* Make the menu become transparent */
  border-radius: 0px;
  border: 0;
  box-shadow: none;
  padding: 0px;
  position: absolute; /* Make the menu out of the document flow so it can placed anywhere without disturbing other widgets */
  top: 0;
  left: 0;
  right: 0;
  z-index: 0; /* If you delete this line, your menu link won't be clicked because it is behind the background. Applying this code bring the menu in front of the background */
}

.navbar-default .navbar-brand {
  font-family: Verdana;
  color: #ffffff;
  font-size: 20px;
}

.navbar-default .navbar-brand:hover,
.navbar-default .navbar-brand:focus {
  color: #ffffff;
  background-color: transparent;
}

.navbar-default .navbar-nav > li > a {
  color: #ffffff;
}

.navbar-default .navbar-nav > li > a:hover,
.navbar-default .navbar-nav > li > a:focus {
  color: #ffffff;
  background-color: transparent;
}

.navbar-default .navbar-toggle {
  border-color: transparent;
}

.navbar-default .navbar-toggle:hover {
  background-color: transparent;
}

.navbar-default .navbar-toggle:focus {
  background-color: transparent;
}

.navbar-default .navbar-toggle .icon-bar {
  background-color: #ffffff;
}
</style>
</head>
<body>
<h1 style="margin:70px;font-size:400%;font-family:微軟正黑體;">{{museum.name}}的評價</h1>
<div class="container-fluid main">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
<div class="w3-top">
  <div class="w3-bar w3-black w3-card-2">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="/team2/my.html" class="w3-bar-item w3-button w3-padding-large">首頁</a>
    <div class="w3-dropdown-hover w3-hide-small">
      <button class="w3-padding-large w3-button" title="More">地區劃分<i class="fa fa-caret-down"></i></button>     
      <div class="w3-dropdown-content w3-bar-block w3-card-4">

          {% for i in area %}
          <a href="/team2/{{i.pk}}" class="w3-bar-item w3-button">{{i.area}}</a>
          {% endfor %}
      </div>
    </div>
    <div class="w3-dropdown-hover w3-hide-small">
      <button class="w3-padding-large w3-button" title="More">性質劃分<i class="fa fa-caret-down"></i></button>     
      <div class="w3-dropdown-content w3-bar-block w3-card-4">
          {% for i in m_type %}
          <a href="/team2/t{{i.pk}}" class="w3-bar-item w3-button">{{i.m_type}}</a>
          {% endfor %}
      </div>
    </div>
    <a href="/team2/about.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small">關於我們</a>

  </div>
</div>
      <!--<div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          
          </ul>
        </div>-->
      </div>
     </nav>
</div>
<table align="center"  style="border-collapse:separate; border-spacing:40px 10px;"> 
<td>
    <tr valign="top">
       <th>
        {% if museum.comment_set.all %}
            <p>目前共有{{museum.comment_set.all|length }}條評價</p>
            <table>
                <tr>
                    <th>留言者</th>
                    <th>評價</th>
                </tr>
            {% for c in museum.comment_set.all %}
                <tr>
                    <td> {{ c.user }} </td>
                    <td> {{ c.content }} </td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p>無評價</p>
        {% endif %}
      </th> 
    <th>
      <form action="" method="post">{% csrf_token %}
            
            <table>
                <tr style="text-align:left;">
                    <td> <label for="user">留言者:</label> </td>
                    <td> <input id="user" type="text" name="user"> </td>
                </tr>
                <tr style="text-align:left;">
                    <td> <label for="content">評價:</label> </td>
                    <td> 
                        <textarea id="content" rows="10" cols="48" name="content"></textarea>
                    </td>
                </tr>
            </table>
            <input type="submit" value="給予評價">
            <input type="button" onclick="history.back()" value="回上一頁" >
        </form>
    </th>
</td>
</table>
        


        
    </body>
</html>

107-team2/team2/ntust/mysite/team2/templates/team2/m_type.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
    <meta name = "format-detection" content = "telephone=no" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" >
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"  />
    <link  rel="stylesheet" media="screen" href="{% static 'css/style.css' %}">
    <link  rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-1.1.1.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script> 
    <script src="{% static 'js/jquery.equalheights.js' %}"></script>
    <script src="{% static 'js/superfish.js' %}"></script>
    <script  src="{% static 'js/jquery.responsivemenu.js' %}"></script>
    <script  src="{% static 'js/jquery.mobilemenu.js' %}"></script>
    <script  src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<style>

body {font-family: "Lato", sans-serif,微軟正黑體;}

.mySlides {display: none}
</style>
</head>
<body>
	<div class="container-fluid main">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
<div class="w3-top">
  <div class="w3-bar w3-black w3-card-2">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="/team2/my.html" class="w3-bar-item w3-button w3-padding-large">首頁</a>
    <div class="w3-dropdown-hover w3-hide-small">
      <button class="w3-padding-large w3-button" title="More">地區劃分<i class="fa fa-caret-down"></i></button>     
      <div class="w3-dropdown-content w3-bar-block w3-card-4">

          {% for i in area %}
          <a href="/team2/{{i.pk}}" class="w3-bar-item w3-button">{{i.area}}</a>
          {% endfor %}
      </div>
    </div>
    <div class="w3-dropdown-hover w3-hide-small">
      <button class="w3-padding-large w3-button" title="More">性質劃分<i class="fa fa-caret-down"></i></button>     
      <div class="w3-dropdown-content w3-bar-block w3-card-4">
          {% for i in m_type1 %}
          <a href="/team2/t{{i.pk}}" class="w3-bar-item w3-button">{{i.m_type}}</a>
          {% endfor %}
      </div>
    </div>
    <a href="/team2/about.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small">關於我們</a>
    
    
  </div>
</div>
      <!--<div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          
          </ul>
        </div>-->
      </div>
     </nav>
</div>
<div class="content projects">
    <div class="container_12">
    <div class="grid_12">
      <h1 style="font-family:微軟正黑體;margin-top:70px;margin-bottom:70px;font-size:400%">{{m_type.m_type}}</h1>
    </div>

    {% for i in m_type.museum_set.all %}    
    {% if forloop.counter|divisibleby:'4' %}
        <td>
          <div class="grid_3">
            <div class="box ic">
              <div class="maxheight">
                  <h2  style="font-family:微軟正黑體;">{{i.name}}</h2><h4 style="font-family:微軟正黑體;">{{i.area}}</h4><i class=" fa fa-cloud"></i>
                  <p><img src="/media/{{ i.img }}" alt=""/ style="width:200px;height:150px;"></p>
                  
                  <p><a href="/team2/m{{ i.pk }}" class="btn">read more</a></p>
              </div>
        </td>

      </table>
        {% else %}
      <table>
          <tr>
            <div class="grid_3">
            <div class="box ic">
              <div class="maxheight">
                  <h2 style="font-family:微軟正黑體;">{{i.name}}</h2><h4 style="font-family:微軟正黑體;">{{i.area}}</h4><i class=" fa fa-cloud"></i>
                  <p><img src="/media/{{ i.img }}" alt=""/ style="width:200px;height:150px;"></p>
                  
                  <p><a href="/team2/m{{ i.pk }}" class="btn">read more</a></p>
              </div>
           </td>
     {% endif %}   
    {% endfor %}
    </table>
</body>
</html>